feat(contest): diffferent challenge style (#251)
* perf(test): remove AccountContext forces a one-second wait

Because tornado.create_signed_value uses int(clock()) as the timestamp,
it causes the signed values to be identical within the same second. This
leads to errors in AccountContext session operations. To avoid this,
AccountContext forces a one-second wait to ensure the timestamps are
different, which makes the test execution slower.

To address this, we introduced the dowhen package and changed the
timestamp from int(clock()) to clock(), so that AccountContext no longer
needs to wait for a second, thus speeding up the test process.

* perf(test): cache judge image to reduce build time

* perf(test): cache project dependency in unit test

* perf(docker): apt do not install unused package

Obviously, libx11 and libxcb are unnecessary

* fix(tests): try to fix weird error in integrated test

Maybe HTTP Keep-Alive cause.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.14/asyncio/runners.py", line 127, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.14/asyncio/base_events.py", line 719, in
run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/ntoj/tests/integrated/main.py", line 209, in test_main
    r = await f()
        ^^^^^^^^^
  File "/ntoj/tests/integrated/submit.py", line 9, in main
    with AccountContext('test1@test', 'test') as user_session:
         ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/ntoj/tests/integrated/util.py", line 233, in __exit__
    res = json.loads(res.text)
  File "/usr/local/lib/python3.14/json/__init__.py", line 352, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.14/json/decoder.py", line 345, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/json/decoder.py", line 363, in
raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

* perf(test): cache backend image building layers

* chore: update poetry lock

* fix(contests): problem add select input for IOI Score Type

* feat(contests): add ACM/ICPC general config

Penalty value, default set submit cd time to 1 secs.
Show IOI Score Type in IOI Mode.

* feat(contests): add ICPC Scoreboard

* feat(contests): do not show score in ICPC Style proset

* feat(contests): add challenge result style config

* feat(contests): add different challenge result style

* fix(contests): replace badge numbers with table layout to avoid color conflicts

* fix(contest): failed to update contest

* fix: reported by copilot