fix(tests): try to fix weird error in integrated test
Maybe HTTP Keep-Alive cause.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.14/asyncio/runners.py", line 127, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.14/asyncio/base_events.py", line 719, in
run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/ntoj/tests/integrated/main.py", line 209, in test_main
    r = await f()
        ^^^^^^^^^
  File "/ntoj/tests/integrated/submit.py", line 9, in main
    with AccountContext('test1@test', 'test') as user_session:
         ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/ntoj/tests/integrated/util.py", line 233, in __exit__
    res = json.loads(res.text)
  File "/usr/local/lib/python3.14/json/__init__.py", line 352, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.14/json/decoder.py", line 345, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/json/decoder.py", line 363, in
raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```